import Head from 'next/head'
import dynamic from 'next/dynamic'

const Sidebar= dynamic(
  () => import('../components/Sidebar'),
  { ssr: false }
);

export default function Home() {
  return (
    <div>
      <Head>
        <title>Speakify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Sidebar/>
    </div>
  )
}
